### ISSUE TITLE
readHTMLTable() function call broken

### ISSUE THREAD

**Issue by stineb** [EcoForecast/EF_Activities#14]
Knitting the Exercise_03_BigData.Rmd file fails due to an error on line 75:

`fia_table = readHTMLTable(fia_html)[[6]]`

Error message:

`Warning: XML content does not seem to be XML:`

The preceeding statement `getURL("http://apps.fs.fed.us/fiadb-downloads/datamart.html")` returns an empty character (`""`). Apparently, the site no longer exists. Probably worth finding another example here?

**Comment by mdietze** [comment]
Thanks for the bug report. This appears to be an issue with a change in URL -- I've updated that URL as well as the URLs in questions 1 and 2. Let me know if you run into any other issues
