### ISSUE TITLE
MODISTools package not working with latest API updates

### ISSUE THREAD

**Issue by stineb** [EcoForecast/EF_Activities#15]
Knitting the Exercise_03_BigData.Rmd file fails due to an error on line 214:

`GetProducts()`

Error message:

`Error in GetProducts() : MODIS Collection 5 Web Service Disabled, See https://daac.ornl.gov/modiswebservice/ for C6 Web Service`

This is a known issue, see [here](https://github.com/seantuck12/MODISTools/issues/44).

**Comment by mdietze** [comment]
Thanks for catching that. Just updated the instructions to have people grab the library from ORNL DAAC. Just tested and it seems to work -- fixed in PR 77b7921.
